theme: minima
title: My homepage
author:
  name: Maarten Visscher
  email: "mail@maartenvisscher.nl"
# description: TODO

minima:
  skin: auto
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/mhvis"
    - title: Strava
      icon: strava
      url: "https://www.strava.com/athletes/122372338"
  hide_site_feed_link: true
  show_excerpts: true
